language: go

go:
  - tip

install:
    - go get -v -t ./...
    - go get github.com/onsi/gomega
    - go install github.com/onsi/ginkgo/ginkgo
    - export PATH=$PATH:$HOME/gopath/bin

script:
    make test
