#!/bin/bash

# colors
OK="\033[32m"
FAIL="\033[31m"
RESET="\033[0m"

# variables
APP="/etc/goproxy/GoProxy"

function is_running() {
    return $(ps ax | grep -v grep | grep GoProxy > /dev/null)
}

function start {
    if is_running
    then
        echo "GoProxy already running"
        exit 1
    fi

    echo -n "Starting GoProxy... "
    $APP &
    echo -e "${OK}✔${RESET}"
}

function stop {
    if ! is_running
    then
        echo "GoProxy is not running"
        exit 1
    fi

    echo -n "Stopping GoProxy... "
    sudo kill $(ps ceo pid=,comm= | awk '/GoProxy/ { print $1; exit }')
    echo -e "${OK}✔${RESET}"
}

function status {
    if is_running
    then
        echo -e "GoProxy is ${OK}running${RESET}"
    else
        echo -e "GoProxy is ${OK}not running${RESET}"
    fi
    exit 1
}

function echo_usage {
    echo "GoProxy service."
    echo $"Usage $0 {start|stop|restart|status}"
    exit 1
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    *)
        echo_usage
esac
